const fakeProductData = [
    {
      productID: 1,
      name: "Product 1",
      shortName: "Prod 1",
      imgUrl: "img1.png",
      imgUrlSmall:"thumb1.png",
      description: "This is the first product description.",
      bgColor: "#017143",
      iconColor: "#333",
      categoryID: 101,
      orderNum: 1,
    },
    {
      productID: 2,
      name: "Product 2",
      shortName: "Prod 2",
      imgUrl: "img2.png",
      imgUrlSmall:"thumb2.png",
      description: "This is the second product description.",
      bgColor: "#eb7495",
      iconColor: "#ff9900",
      categoryID: 102,
      orderNum: 2,
    },
    {
      productID: 3,
      name: "Product 3",
      shortName: "Prod 3",
      imgUrl: "img3.png",
      imgUrlSmall:"thumb3.png",
      description: "This is the third product description.",
      bgColor: "#d752b1",
      iconColor: "#00cc66",
      categoryID: 103,
      orderNum: 3,
    },
    {
      productID: 4,
      name: "Product 4",
      shortName: "Prod 4",
      imgUrl: "img4.png",
      imgUrlSmall:"thumb4.png",
      description: "This is the third product description.",
      bgColor: "#d752b1",
      iconColor: "#00cc66",
      categoryID: 104,
      orderNum: 4,
    },
    {
      productID: 5,
      name: "Product 5",
      shortName: "Prod 5",
      imgUrl: "img5.png",
      imgUrlSmall:"thumb5.png",
      description: "This is the third product description.",
      bgColor: "#d752b1",
      iconColor: "#00cc66",
      categoryID: 105,
      orderNum: 5,
    },
  ];
  
  export default fakeProductData;
  